---
title: Een Scratch-account aanmaken
hero_image: images/banner.png
description: maak een Scratch account beschrijving
version: 4
listed: false
copyedit: false
last_tested: "2020-06-23"
steps:
  - 
    title: Inleiding
