title: Create a scratch account
hero_image: images/banner.png
description: create-scratch-account description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-23"
steps:
  - title: Introduction
