---
title: Scratch ఖాతాను సృష్టించండి
hero_image: images/banner.png
description: create-scratch-account వివరణ
version: 4
listed: false
copyedit: false
last_tested: "2020-06-23"
steps:
  - title: పరిచయం
