---
title: Crie uma conta Scratch
hero_image: images/banner.png
description: descrição create-scratch-account
version: 4
listed: false
copyedit: false
last_tested: "2020-06-23"
steps:
  - 
    title: Introdução
