---
title: Crea una cuenta de Scratch
hero_image: images/banner.png
description: descripción crear-cuenta-scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-06-23"
steps:
  - 
    title: Introducción
