---
title: Créer un compte Scratch
hero_image: images/banner.png
description: description créer-compte-scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-06-23"
steps:
  - title: Introduction
